routes/web.php
<?php

    use App\Http\Controllers\BinnenlandController;
    use App\Http\Controllers\SendEmailController;
    use Illuminate\Support\Facades\Auth;
    use Illuminate\Support\Facades\Mail;
    use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/binnenland', BinnenlandController::class);

Route::resource('/economie', \App\Http\Controllers\EconomieController::class);

Route::resource('/sport', \App\Http\Controllers\SportController::class);

Route::get('/', [\App\Http\Controllers\HomeController::class, 'index']);

Route::get('/about', function () {
    return view('home.about');
});


Route::get('/contact', '\App\Http\Controllers\SendEmailController@index')->middleware('auth');
Route::post('/contact/send', '\App\Http\Controllers\SendEmailController@send')->name('contact.send');

Route::get('/login', function () {
    redirect(\route('login'));
});

Route::post('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('send-mail', function () {

    $details = [
        'title' => 'Mail from ItSolutionStuff.com',
        'body' => 'This is for testing email using smtp'
    ];

    Mail::to('your_receiver_email@gmail.com')->send(new \App\Mail\MyTestMail($details));

    dd("Email is Sent.");
});

app/Models/Sport.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sport extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'body', 'writer', 'image'];
}

app/Http/Controllers/SportController.php
<?php

namespace App\Http\Controllers;

use App\Models\Sport;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class SportController extends Controller
{

    /**
     * SportController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sports = Sport::all()->sort(function ($a, $b){
            return strtotime($b->updated_at) - strtotime($a->updated_at);
        });

        return view('sport.index', compact('sports'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('sport.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required | max:255',
            'body' => 'required | max:255',
            'writer' => 'required | max:255',
            'image' => 'required'
        ],
            [
                'title.required' => 'U bent vergeten een titel toe te voegen!',
                'body.required' => 'U bent vergeten een alinea te schrijven!',
                'writer.required' => 'U bent vergeten de schrijver toe te voegen!',
                'image.required' => 'U bent vergeten een afbeelding toe te voegen!',
                '.max' => 'U heeft meer dan 255 characters!'
            ]);

        if($request->hasFile('image')){
            $image = time(). $request->file('image')->getClientOriginalName();
            $request->image->storeAs('sports', $image, 'public');
        } else {
            $image = null;
        }

        $sport = new Sport();

        $sport->title = $request->input('title');
        $sport->body = $request->input('body');
        $sport->writer = $request->input('writer');

        $sport->image = $image;
        $sport->save();

        return redirect(route('sport.index'))->with('status', 'Artikel succesvol aangemaakt');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Sport  $sport
     * @return \Illuminate\Http\Response
     */
    public function show(Sport $sport)
    {
        return view('sport.show', ['sport' => $sport]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Sport  $sport
     * @return \Illuminate\Http\Response
     */
    public function edit(Sport $sport)
    {
        return view('sport.edit', ['sport' => $sport]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Sport  $sport
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Sport $sport)
    {
        $request->validate([
            'title' => 'required | max:255' ,
            'body' => 'required | max:255',
            'writer' => 'required | max:255',
        ],
            [
                'title.required' => 'U bent vergeten een titel toe te voegen!',
                'body.required' => 'U bent vergeten een alinea te schrijven!',
                'writer.required' => 'U bent vergeten de schrijver toe te voegen!',
                '.max' => 'U heeft meer dan 255 characters!'
            ]);

        $image = $request->has('file') ? time(). $request->file('image')->getClientOriginalName() : $sport->image;

        if ($request->has('image')){
            Storage::delete('/storage/sports/'. $sport->image);
            unlink(public_path('storage/sports/') . $sport->image);

            $request->image->storeAs('sports', $image, 'public');
        }

        $sport->update([
            'title' => $request->title,
            'body' => $request->body,
            'writer' => $request->writer,
            'image' => $image,
        ]);

        return redirect(route('sport.index'))->with('status', $sport->title. ' is bijgewerkt');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Sport  $sport
     * @return \Illuminate\Http\Response
     */
    public function destroy(Sport $sport)
    {
        unlink(public_path('storage/sports/') . $sport->image);

        $sport->delete();

        return redirect(route('sport.index'))->with('status', 'Artikel succesvol verwijderd');
    }
}

resources/views/sport/create.blade.php
@extends('common.master')

@section('content')
    <section id="sliderSection">
        <div class="fashion_technology_area">
            <div class="left_content">
                <div class="single_post_content">
                    @auth
                        <h2><span>Maak &nbsp sport &nbsp artikel &nbsp aan</span></h2>
                        <br>
                        <div class="media wow fadeInDown">
                            <!-- Begin Edit form -->
                            <form method="POST" action="{{ route('sport.store') }}" enctype="multipart/form-data">
                                @csrf

                                <br>
                                <div class="field">
                                    <label>Titel</label>
                                    <div class="control">
                                        <input name="title" class="form-control @error('title') is-danger @enderror"
                                               type="text" placeholder="De titel hier..."
                                               value="{{ old('title') }}" width="500"
                                        >
                                    </div>
                                    @error('title')
                                    <p class="alert alert-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <br>
                                <div class="field">
                                    <label>Artikel</label>
                                    <div class="control">
                                        <textarea name="body" id="body" cols="30" rows="10" class="form-control @error('body')
                                            is-danger @enderror" placeholder="Schrijf het artikel hier..." >{{ old('body') }}</textarea>

                                    </div>
                                    @error('body')
                                    <p class="alert alert-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <br>
                                <div class="field">
                                    <label>Schrijver naam</label>
                                    <div class="control">
                                        <input name="writer" class="form-control @error('writer') is-danger @enderror"
                                               type="text" placeholder="Uw naam hier..."
                                               value="{{ old('writer') }}"
                                        >
                                    </div>
                                    @error('writer')
                                    <p class="alert alert-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <br>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <label class="custom-file-label">Upload afbeelding</label>
                                        <input name="image" id="image" type="file" class="custom-file-input">
                                    </div>
                                    @error('image')
                                    <p class="alert alert-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <br>
                                <div class="row">
                                    <br>
                                    <br>
                                    <button class="btn" type="submit">Artikel opslaan</button>
                                    <br>
                                    <br>
                                </div>
                            </form>
                            <!-- End Edit form -->
                        </div>
                    @endauth

                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/sport/edit.blade.php
@extends('common.master')

@section('content')
    <section id="sliderSection">
        <div class="fashion_technology_area">
            <div class="left_content">
                <div class="single_post_content">
                    @auth
                        <h2><span>Bewerk uw artikel</span></h2>
                        <br>
                        <div class="media wow fadeInDown">
                            <!-- Begin Edit form -->
                            <form method="POST" action="{{ route('sport.update', $sport) }}" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')

                                <br>
                                <div class="field">
                                    <label>Titel</label>
                                    <div class="control">
                                        <input name="title" class="form-control @error('title') is-danger @enderror"
                                               type="text" placeholder="De titel hier..."
                                               value="{{ old('title', $sport->title) }}" width="500"
                                        >
                                    </div>
                                    @error('title')
                                    <p class="alert alert-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <br>
                                <div class="field">
                                    <label>Artikel</label>
                                    <div class="control">
                                        <textarea name="body" id="body" cols="30" rows="10" class="form-control @error('body')
                                            is-danger @enderror" placeholder="Schrijf het artikel hier..." >{{ old('body', $sport->body) }}</textarea>

                                    </div>
                                    @error('body')
                                    <p class="alert alert-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <br>
                                <div class="field">
                                    <label>Schrijver naam</label>
                                    <div class="control">
                                        <input name="writer" class="form-control @error('writer') is-danger @enderror"
                                               type="text" placeholder="Uw naam hier..."
                                               value="{{ old('writer', $sport->writer) }}"
                                        >
                                    </div>
                                    @error('writer')
                                    <p class="alert alert-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <br>
                                <div>
                                    <p>Huidige afbeelding:</p>
                                    @if($sport->image)
                                        <img src="{{asset('/storage/sports/'. $sport->image)}}" alt="" height="200">
                                    @else
                                        <br>
                                        <p>Geen huidige afbeelding voor dit artikel</p>
                                        <br>
                                    @endif
                                </div>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <label class="custom-file-label">Verander afbeelding</label>
                                        <input name="image" id="image" type="file" class="custom-file-input">
                                    </div>
                                </div>
                                <br>
                                <div class="row">
                                    <button class="btn" type="submit">Opslaan</button>
                                    <br><br>
                                </div>
                            </form>
                                <div class="row">
                                    <form action="{{ route('sport.show', $sport) }}" >
                                        <button class="btn" type="submit">Ga terug</button>
                                        <br>
                                        <br>
                                    </form>
                                </div>
                                <div class="row">
                                    <form action="{{ route('sport.destroy', $sport) }}" method="POST">
                                        @csrf
                                        @method('DELETE')

                                        <button class="btn" type="submit">Verwijder artikel</button>
                                        <br>
                                        <br>
                                    </form>
                                </div>
                            <!-- End Edit form -->
                        </div>
                    @endauth

                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/sport/index.blade.php
@extends('common.master')

@section('content')
<section id="contentSection">
    <div class="row">
        <div class="col-lg-16 col-md-16 col-sm-16">
            <div class="left_content">
                <div class="single_post_content">
                    <h2><span>Sport</span></h2>

                    <div>
                        @if(session('status'))
                            <div class="message is-primary">
                                <div class="message-header">
                                    {{session('status')}}
                                    <form action="{{ route('sport.index') }}">
                                        <button type="submit">OK</button>
                                    </form>
                                </div>
                            </div>
                        @endif
                    </div>

                    @auth
                    <br>
                    <form action="{{ route('sport.create') }}">
                        <button class="btn" type="submit">Maak sport artikel aan</button>
                    </form>
                    <br>
                    @endauth
                    @foreach($sports as $sport)
                        <div class="media wow fadeInDown"> <a href="{{ route('sport.show', $sport) }}" class="featured_img"> <img alt="" src="{{ asset('/storage/sports/'. $sport->image) }}" height="400"> </a>
                            <div>
                                <a href="{{ route('sport.show', $sport) }}">
                                    <div>
                                        {{ $sports->title }} <br>
                                    </div>
                                </a>
                                <div>
                                    {{ $sport->created_at }}
                                    <br>
                                    <br>
                                    <br>
                                    <br>
                                    <br>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/sport/show.blade.php
@extends('common.master')

@section('content')
    <section id="contentSection">
        <div class="row">
            <div class="col-lg-16 col-md-16 col-sm-16">
                <div class="left_content">
                    <div class="single_post_content">
                        <h2><span>{{ $sport->title }}</span></h2>
                        @auth
                            <br>
                            <form action="{{ route('sport.edit', $sport) }} " class="media wow fadeInDown">
                                <button class="btn" type="submit">Bewerk deze pagina</button>
                            </form>
                            <br>
                        @endauth
                        <div class="media wow fadeInDown"><img alt="" src="{{ asset('/storage/sports/'. $sport->image) }}" height="950">
                            <div>
                                <br>
                                <br>
                                {{ $sport->body }}
                                <br>
                                <br>
                                Schrijver: &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                                    {{ $sport->writer }}<br>
                                Aangemaakt op: &nbsp&nbsp{{ $sport->created_at }}<br>
                                Geupdate op: &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ $sport->updated_at }}<br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection