routes/web.php
<?php

    use App\Http\Controllers\BinnenlandController;
    use App\Http\Controllers\SendEmailController;
    use Illuminate\Support\Facades\Auth;
    use Illuminate\Support\Facades\Mail;
    use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/binnenland', BinnenlandController::class);

Route::resource('/economie', \App\Http\Controllers\EconomieController::class);

Route::resource('/sport', \App\Http\Controllers\SportController::class);

Route::get('/', [\App\Http\Controllers\HomeController::class, 'index']);

Route::get('/about', function () {
    return view('home.about');
});


Route::get('/contact', '\App\Http\Controllers\SendEmailController@index')->middleware('auth');
Route::post('/contact/send', '\App\Http\Controllers\SendEmailController@send')->name('contact.send');

Route::get('/login', function () {
    redirect(\route('login'));
});

Route::post('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('send-mail', function () {

    $details = [
        'title' => 'Mail from ItSolutionStuff.com',
        'body' => 'This is for testing email using smtp'
    ];

    Mail::to('your_receiver_email@gmail.com')->send(new \App\Mail\MyTestMail($details));

    dd("Email is Sent.");
});

app/Models/Binnenland.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Binnenland extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'body', 'writer', 'image'];
}

app/Http/Controllers/BinnenlandController.php
<?php

namespace App\Http\Controllers;

use App\Models\Binnenland;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class BinnenlandController extends Controller
{

    /**
     * BinnenlandController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        $binnenlands = Binnenland::all()->sort(function ($a, $b){
            return strtotime($b->updated_at) - strtotime($a->updated_at);
        });

        return view('binnenland.index', compact('binnenlands'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('binnenland.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required | max:255',
            'body' => 'required | max:255',
            'writer' => 'required | max:255',
            'image' => 'required'
        ],
        [
            'title.required' => 'U bent vergeten een titel toe te voegen!',
            'body.required' => 'U bent vergeten een alinea te schrijven!',
            'writer.required' => 'U bent vergeten de schrijver toe te voegen!',
            'image.required' => 'U bent vergeten een afbeelding toe te voegen!',
            'title.max' => 'U heeft meer dan 255 characters!',
            'body.max' => 'U heeft meer dan 255 characters!',
            'writer.max' => 'U heeft meer dan 255 characters!',
        ]);

        if($request->hasFile('image')){
            $image = time(). $request->file('image')->getClientOriginalName();
            $request->image->storeAs('binnenlands', $image, 'public');
        } else {
            $image = null;
        }

        $binnenland = new Binnenland();

        $binnenland->title = $request->input('title');
        $binnenland->body = $request->input('body');
        $binnenland->writer = $request->input('writer');

        $binnenland->image = $image;
        $binnenland->save();

        return redirect(route('binnenland.index'))->with('status', 'Artikel succesvol aangemaakt');
    }



    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Binnenland  $binnenland
     */
    public function show(Binnenland $binnenland)
    {
        return view('binnenland.show', ['binnenland' => $binnenland]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Binnenland  $binnenland
     */
    public function edit(Binnenland $binnenland)
    {
        return view('binnenland.edit', ['binnenland' => $binnenland]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Binnenland  $binnenland
     */
    public function update(Request $request, Binnenland $binnenland)
    {
        $request->validate([
            'title' => 'required | max:255' ,
            'body' => 'required | max:255',
            'writer' => 'required | max:255',
        ],
        [
            'title.required' => 'U bent vergeten een titel toe te voegen!',
            'body.required' => 'U bent vergeten een alinea te schrijven!',
            'writer.required' => 'U bent vergeten de schrijver toe te voegen!',
            '.max' => 'U heeft meer dan 255 characters!'
        ]);

        $image = $request->has('file') ? time(). $request->file('image')->getClientOriginalName() : $binnenland->image;

        if ($request->has('image')){
            Storage::delete('storage/binnenlands/'. $binnenland->image);
            unlink(public_path('storage/binnenlands/') . $binnenland->image);

            $request->image->storeAs('binnenlands', $image, 'public');
        }

        $binnenland->update([
           'title' => $request->title,
            'body' => $request->body,
            'writer' => $request->writer,
            'image' => $image,
        ]);

        return redirect(route('binnenland.index'))->with('status', $binnenland->title. ' is bijgewerkt');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Binnenland  $binnenland
     */
    public function destroy(Binnenland $binnenland)
    {
        unlink(public_path('storage/binnenlands/') . $binnenland->image);

        $binnenland->delete();

        return redirect(route('binnenland.index'))->with('status', 'Artikel succesvol verwijderd');
    }

}

resources/views/binnenland/create.blade.php
@extends('common.master')

@section('content')
    <section id="sliderSection">
        <div class="fashion_technology_area">
            <div class="left_content">
                <div class="single_post_content">
                    @auth
                        <h2><span>Maak &nbsp binnenland &nbsp artikel &nbsp aan</span></h2>
                        <br>
                        <div class="media wow fadeInDown">
                            <!-- Begin Edit form -->
                            <form method="POST" action="{{ route('binnenland.store') }}" enctype="multipart/form-data">
                                @csrf

                                <div class="field">
                                    <label>Uitleg</label>
                                    <div>
                                        <p>Als er een * achter het kopje staat betekend dit dat dit veld verplicht is in te vullen.</p>
                                        <br>
                                        <p>De velden mogen maximaal 255 characters bevatten.</p>
                                    </div>
                                    <br>
                                </div>
                                <div class="field">
                                    <label>Titel *</label>
                                    <div class="control">
                                        <input required name="title" class="form-control @error('title') is-danger @enderror"
                                               type="text" placeholder="De titel hier..."
                                               value="{{ old('title') }}" width="500"
                                        >
                                    </div>
                                    @error('title')
                                    <p class="alert alert-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <br>
                                <div class="field">
                                    <label>Artikel *</label>
                                    <div class="control">
                                        <textarea required name="body" id="body" cols="30" rows="10" class="form-control @error('body')
                                            is-danger @enderror" placeholder="Schrijf het artikel hier..." >{{ old('body') }}</textarea>

                                    </div>
                                    @error('body')
                                    <p class="alert alert-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <br>
                                <div class="field">
                                    <label>Schrijver naam *</label>
                                    <div class="control">
                                        <input required name="writer" class="form-control @error('writer') is-danger @enderror"
                                               type="text" placeholder="Uw naam hier..."
                                               value="{{ old('writer') }}"
                                        >
                                    </div>
                                    @error('writer')
                                    <p class="alert alert-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <br>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <label class="custom-file-label">Upload afbeelding *</label>
                                        <input required name="image" id="image" type="file" class="custom-file-input">
                                    </div>
                                    @error('image')
                                    <p class="alert alert-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <br>
                                <div class="row">
                                    <br>
                                    <br>
                                    <button class="btn" type="submit">Artikel opslaan</button>
                                    <br>
                                    <br>
                                </div>
                            </form>
                            <!-- End Edit form -->
                        </div>
                    @endauth

                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/binnenland/edit.blade.php
@extends('common.master')

@section('content')
    <section id="sliderSection">
        <div class="fashion_technology_area">
            <div class="left_content">
                <div class="single_post_content">
                    @auth
                        <h2><span>Bewerk uw artikel</span></h2>
                        <br>
                        <div class="media wow fadeInDown">
                            <!-- Begin Edit form -->
                            <form method="POST" action="{{ route('binnenland.update', $binnenland) }}" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')

                                <br>
                                <div class="field">
                                    <label>Titel</label>
                                    <div class="control">
                                        <input name="title" class="form-control @error('title') is-danger @enderror"
                                               type="text" placeholder="De titel hier..."
                                               value="{{ old('title', $binnenland->title) }}" width="500"
                                        >
                                    </div>
                                    @error('title')
                                    <p class="alert alert-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <br>
                                <div class="field">
                                    <label>Artikel</label>
                                    <div class="control">
                                        <textarea name="body" id="body" cols="30" rows="10" class="form-control @error('body')
                                            is-danger @enderror" placeholder="Schrijf het artikel hier..." >{{ old('body', $binnenland->body) }}</textarea>

                                    </div>
                                    @error('body')
                                    <p class="alert alert-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <br>
                                <div class="field">
                                    <label>Schrijver naam</label>
                                    <div class="control">
                                        <input name="writer" class="form-control @error('writer') is-danger @enderror"
                                               type="text" placeholder="Uw naam hier..."
                                               value="{{ old('writer', $binnenland->writer) }}"
                                        >
                                    </div>
                                    @error('writer')
                                    <p class="alert alert-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                                <br>
                                <div>
                                    <p>Huidige afbeelding:</p>
                                    @if($binnenland->image)
                                        <img src="{{asset('/storage/binnenlands/'. $binnenland->image)}}" alt="" height="200">
                                    @else
                                        <br>
                                        <p>Geen huidige afbeelding voor dit artikel</p>
                                        <br>
                                    @endif
                                </div>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <label class="custom-file-label">Verander afbeelding</label>
                                        <input name="image" id="image" type="file" class="custom-file-input">
                                    </div>
                                </div>
                                <br>
                                <div class="row">
                                    <button class="btn" type="submit">Opslaan</button>
                                    <br><br>
                                </div>
                            </form>
                                <div class="row">
                                    <form action="{{ route('binnenland.show', $binnenland) }}" >
                                        <button class="btn" type="submit">Ga terug</button>
                                        <br>
                                        <br>
                                    </form>
                                </div>
                                <div class="row">
                                    <form action="{{ route('binnenland.destroy', $binnenland) }}" method="POST">
                                        @csrf
                                        @method('DELETE')

                                        <button class="btn" type="submit">Verwijder artikel</button>
                                        <br>
                                        <br>
                                    </form>
                                </div>
                            <!-- End Edit form -->
                        </div>
                    @endauth

                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/binnenland/index.blade.php
@extends('common.master')

@section('content')
<section id="contentSection">
    <div class="row">
        <div class="col-lg-16 col-md-16 col-sm-16">
            <div class="left_content">
                <div class="single_post_content">
                    <h2><span>Binnenland</span></h2>

                    <div>
                        @if(session('status'))
                            <div class="message is-primary">
                                <div class="message-header">
                                    {{session('status')}}
                                    <form action="{{ route('binnenland.index') }}">
                                        <button class="btn" type="submit">OK</button>
                                    </form>
                                </div>
                            </div>
                        @endif
                    </div>

                    @auth
                    <br>
                    <form action="{{ route('binnenland.create') }}">
                        <button class="btn" type="submit">Maak binnenland artikel aan</button>
                    </form>
                    <br>
                    @endauth
                    @foreach($binnenlands as $binnenland)
                        <div class="media wow fadeInDown"> <a href="{{ route('binnenland.show', $binnenland) }}" class="featured_img"> <img alt="" src="{{ asset('/storage/binnenlands/'. $binnenland->image) }}" height="400"> </a>
                            <div>
                                <a href="{{ route('binnenland.show', $binnenland) }}">
                                    <div>
                                        {{ $binnenland->title }} <br>
                                    </div>
                                </a>
                                <div>
                                    {{ $binnenland->created_at }}
                                    <br>
                                    <br>
                                    <br>
                                    <br>
                                    <br>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/binnenland/show.blade.php
@extends('common.master')

@section('content')
    <section id="contentSection">
        <div class="row">
            <div class="col-lg-16 col-md-16 col-sm-16">
                <div class="left_content">
                    <div class="single_post_content">
                        <h2><span>{{ $binnenland->title }}</span></h2>
                        @auth
                            <br>
                            <form action="{{ route('binnenland.edit', $binnenland) }} " class="media wow fadeInDown">
                                <button class="btn" type="submit">Bewerk deze pagina</button>
                            </form>
                            <br>
                        @endauth
                        <div class="media wow fadeInDown"><img alt="" src="{{ asset('/storage/binnenlands/'. $binnenland->image) }}" height="950">
                            <div>
                                <br>
                                <br>
                                {{ $binnenland->body }}
                                <br>
                                <br>
                                Schrijver: &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                                    {{ $binnenland->writer }}<br>
                                Aangemaakt op: &nbsp&nbsp{{ $binnenland->created_at }}<br>
                                Geupdate op: &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ $binnenland->updated_at }}<br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection